Fix missing types/node module
Commit addresses the following error:

vite.config.ts:2:31 - error TS2307: Cannot find module 'node:url' or its corresponding type declarations.